### ISSUE TITLE
Can only export gpio node if gpio_no is a str

### ISSUE THREAD

**Issue by troelsim** [sardok/txgpio#2]
When an `int` is passed as the `gpio_no` argument, it works fine if the given channel is already exported, but if it is not, `_export_gpio` will fail when we try to write an `int` to `/sys/class/gpio/export` without first converting it to a `str`.

I suggest writing simply converting it to a string before writing to sysfs in `_export_gpio` and `_unexport_gpio`, for consistency.

**Comment by sardok** [comment]
Thanks for reporting @troelsim. Fixed on master. Also uploaded the package to pypi.

**Comment by troelsim** [comment]
Great! Thanks! A nice library by the way, it is making my life easier :-)
